#!/usr/bin/env bash
set -euo pipefail

# Generated by scripts/build_real_adapter_handoff.py.
# Run only on the CUDA host with the real trained adapter and matching Docker image.
# This script intentionally keeps M6-RC and v0 NOT_GO until every verifier returns GO.

if [ -n "${MIB_RUNTIME_ALLOW_FAKE_BACKEND:-}" ]; then
  echo "Refusing to run: MIB_RUNTIME_ALLOW_FAKE_BACKEND must be unset." >&2
  exit 2
fi

if [ -z "${MIB_RUNTIME_BEARER_TOKEN:-}" ] || [ "${#MIB_RUNTIME_BEARER_TOKEN}" -lt 32 ] || [ "${MIB_RUNTIME_BEARER_TOKEN}" = "<set-32-plus-character-token>" ]; then
  echo "Refusing to run: set a real MIB_RUNTIME_BEARER_TOKEN with at least 32 characters." >&2
  exit 2
fi

printf '\n== candidate_scan ==\n'
./.venv/bin/python scripts/find_real_adapter_candidates.py --root /home/firewine/MIB-studio --root /tmp/mib-real-adapter --root /tmp/mib-phi-docker-export-_vgqfd4g --base-model microsoft/Phi-3.5-mini-instruct --image mib-export:test --agent-id finance.router.v1 --model-cache-dir /tmp/mib-strict-model-cache-phi/model_cache --json-output artifacts/review/real_adapter_candidate_scan.json

printf '\n== adapter_intake ==\n'
./.venv/bin/python scripts/verify_real_adapter_artifact.py --adapter-dir /tmp/mib-real-adapter/adapter --base-model microsoft/Phi-3.5-mini-instruct --manifest /tmp/mib-real-adapter/manifest.json --json-output artifacts/review/real_adapter_artifact_intake.json

printf '\n== rc_gate_preflight ==\n'
MIB_RUNTIME_BEARER_TOKEN="${MIB_RUNTIME_BEARER_TOKEN}" ./.venv/bin/python scripts/run_m6_real_adapter_rc_gate.py --adapter-dir /tmp/mib-real-adapter/adapter --adapter-manifest /tmp/mib-real-adapter/manifest.json --base-model microsoft/Phi-3.5-mini-instruct --image mib-export:test --agent-id finance.router.v1 --model-cache-dir /tmp/mib-strict-model-cache-phi/model_cache --adapter-intake-json-output artifacts/review/real_adapter_artifact_intake.json --endpoint-output artifacts/review/real_trained_adapter_endpoint_evidence.md --endpoint-json-output artifacts/review/real_trained_adapter_endpoint_evidence.json --m6-json-output artifacts/review/m6_rc_evidence_verification.json --json-output artifacts/review/m6_real_adapter_rc_gate_run.json --preflight-only

printf '\n== rc_gate_endpoint_evidence ==\n'
MIB_RUNTIME_BEARER_TOKEN="${MIB_RUNTIME_BEARER_TOKEN}" ./.venv/bin/python scripts/run_m6_real_adapter_rc_gate.py --adapter-dir /tmp/mib-real-adapter/adapter --adapter-manifest /tmp/mib-real-adapter/manifest.json --base-model microsoft/Phi-3.5-mini-instruct --image mib-export:test --agent-id finance.router.v1 --model-cache-dir /tmp/mib-strict-model-cache-phi/model_cache --adapter-intake-json-output artifacts/review/real_adapter_artifact_intake.json --endpoint-output artifacts/review/real_trained_adapter_endpoint_evidence.md --endpoint-json-output artifacts/review/real_trained_adapter_endpoint_evidence.json --m6-json-output artifacts/review/m6_rc_evidence_verification.json --json-output artifacts/review/m6_real_adapter_rc_gate_run.json --endpoint-evidence-only

printf '\n== m6_review_docs_go_update_required ==\n'
./.venv/bin/python -c 'from pathlib import Path; import sys; signoff=Path('"'"'docs/reviews/M6/SIGNOFF_MATRIX.md'"'"').read_text(encoding='"'"'utf-8'"'"'); cto=Path('"'"'docs/reviews/M6/CTO_DECISION.md'"'"').read_text(encoding='"'"'utf-8'"'"'); ok='"'"'| M6 Export / v0 RC | GO | GO | GO | GO | GO | GO | GO | GO | GO | GO |'"'"' in signoff and '"'"'Decision: GO'"'"' in cto; sys.exit(0 if ok else 3)'

printf '\n== rc_gate_m6_go ==\n'
MIB_RUNTIME_BEARER_TOKEN="${MIB_RUNTIME_BEARER_TOKEN}" ./.venv/bin/python scripts/run_m6_real_adapter_rc_gate.py --adapter-dir /tmp/mib-real-adapter/adapter --adapter-manifest /tmp/mib-real-adapter/manifest.json --base-model microsoft/Phi-3.5-mini-instruct --image mib-export:test --agent-id finance.router.v1 --model-cache-dir /tmp/mib-strict-model-cache-phi/model_cache --adapter-intake-json-output artifacts/review/real_adapter_artifact_intake.json --endpoint-output artifacts/review/real_trained_adapter_endpoint_evidence.md --endpoint-json-output artifacts/review/real_trained_adapter_endpoint_evidence.json --m6-json-output artifacts/review/m6_rc_evidence_verification.json --json-output artifacts/review/m6_real_adapter_rc_gate_run.json --m6-verification-only

printf '\n== evidence_bundle_assembly ==\n'
./.venv/bin/python scripts/build_real_adapter_evidence_bundle.py --source-dir artifacts/review --bundle-dir artifacts/review/real_adapter_evidence_bundle --expected-decision GO --verification-output artifacts/review/real_adapter_evidence_bundle_verification.json --manifest-output artifacts/review/real_adapter_evidence_bundle_manifest.json --archive-output artifacts/review/real_adapter_evidence_bundle.tar.gz

printf '\n== v0_readiness_recheck ==\n'
./.venv/bin/python scripts/verify_v0_release_readiness.py --expected-decision GO --json-output artifacts/review/v0_release_readiness_audit.json
