#!/usr/bin/env bash
set -euo pipefail

# Generated by scripts/prepare_cuda_lora_training_run.py.
# Run only on the CUDA host that will produce the real trained lora_adapter.

if [ -n "${MIB_RUNTIME_ALLOW_FAKE_BACKEND:-}" ]; then
  echo "Refusing to run: MIB_RUNTIME_ALLOW_FAKE_BACKEND must be unset." >&2
  exit 2
fi

if ! command -v nvidia-smi >/dev/null 2>&1; then
  echo "Refusing to run: nvidia-smi is not available." >&2
  exit 2
fi

if [ ! -x ./.venv/bin/llamafactory-cli ]; then
  echo "Refusing to run: LLaMA-Factory CLI is not executable: ./.venv/bin/llamafactory-cli" >&2
  exit 2
fi

if [ ! -d /tmp/mib-strict-model-cache-phi/model_cache ]; then
  echo "Refusing to run: model cache directory is missing: /tmp/mib-strict-model-cache-phi/model_cache" >&2
  exit 2
fi

if [ ! -f /tmp/mib-real-adapter/backend_config.yaml ]; then
  echo "Refusing to run: backend_config.yaml is missing under /tmp/mib-real-adapter" >&2
  exit 2
fi

printf '\n== preflight_cuda_training ==\n'
./.venv/bin/python scripts/check_cuda_lora_training_prereqs.py --dataset-jsonl examples/fixtures/router_20.jsonl --base-model microsoft/Phi-3.5-mini-instruct --model-cache-dir /tmp/mib-strict-model-cache-phi/model_cache --output-root /tmp/mib-real-adapter --backend-config /tmp/mib-real-adapter/backend_config.yaml --image mib-export:test --llamafactory-cli ./.venv/bin/llamafactory-cli --verify-model-cache-hashes --json-output artifacts/review/real_adapter_cuda_training_prereq_preflight.json

printf '\n== train_real_adapter ==\n'
./.venv/bin/llamafactory-cli train /tmp/mib-real-adapter/backend_config.yaml

printf '\n== finalize_manifest ==\n'
./.venv/bin/python scripts/prepare_cuda_lora_training_run.py --finalize-only --base-model microsoft/Phi-3.5-mini-instruct --output-root /tmp/mib-real-adapter --json-output artifacts/review/real_adapter_cuda_training_finalize.json

printf '\n== verify_adapter_intake ==\n'
./.venv/bin/python scripts/verify_real_adapter_artifact.py --adapter-dir /tmp/mib-real-adapter/adapter --base-model microsoft/Phi-3.5-mini-instruct --manifest /tmp/mib-real-adapter/manifest.json --json-output artifacts/review/real_adapter_artifact_intake.json

printf '\n== prepare_docker_image ==\n'
./.venv/bin/python scripts/prepare_real_adapter_docker_image.py --adapter-root /tmp/mib-real-adapter --base-model microsoft/Phi-3.5-mini-instruct --agent-id finance.router.v1 --image mib-export:test --context-output /tmp/mib-real-adapter/docker_context --json-output artifacts/review/real_adapter_docker_image_handoff.json --markdown-output artifacts/review/real_adapter_docker_image_handoff.md --shell-output artifacts/review/real_adapter_docker_image_handoff.sh

printf '\n== run_rc_handoff ==\n'
bash artifacts/review/real_adapter_cuda_handoff.sh
