#!/usr/bin/env bash
set -euo pipefail

# Generated by scripts/prepare_real_adapter_docker_image.py.
# Run only after the real adapter exists under the configured adapter root.

if [ -n "${MIB_RUNTIME_ALLOW_FAKE_BACKEND:-}" ]; then
  echo "Refusing to run: MIB_RUNTIME_ALLOW_FAKE_BACKEND must be unset." >&2
  exit 2
fi

if [ -z "${MIB_DOCKER_BASE_IMAGE_WITH_DIGEST:-}" ]; then
  echo "Refusing to run: MIB_DOCKER_BASE_IMAGE_WITH_DIGEST is required." >&2
  exit 2
fi

case "${MIB_DOCKER_BASE_IMAGE_WITH_DIGEST}" in
  *@sha256:*) ;;
  *) echo "Refusing to run: MIB_DOCKER_BASE_IMAGE_WITH_DIGEST must include @sha256." >&2; exit 2 ;;
esac

printf '\n== materialize_context ==\n'
./.venv/bin/python scripts/prepare_real_adapter_docker_image.py --materialize-context --adapter-root /tmp/mib-real-adapter --base-model microsoft/Phi-3.5-mini-instruct --agent-id finance.router.v1 --image mib-export:test --context-output /tmp/mib-real-adapter/docker_context --json-output artifacts/review/real_adapter_docker_image_context.json

printf '\n== build_image ==\n'
docker build --pull=false --build-arg BASE_IMAGE_WITH_DIGEST="${MIB_DOCKER_BASE_IMAGE_WITH_DIGEST}" -t mib-export:test /tmp/mib-real-adapter/docker_context

printf '\n== inspect_image ==\n'
docker image inspect mib-export:test
