#!/usr/bin/env bash
set -euo pipefail

# Generated by scripts/build_verified_cuda_training_launcher.py.
# Run this on the external CUDA host instead of invoking the training handoff directly.

if [ -n "${MIB_RUNTIME_ALLOW_FAKE_BACKEND:-}" ]; then
  echo "Refusing to run: MIB_RUNTIME_ALLOW_FAKE_BACKEND must be unset." >&2
  exit 2
fi

if [ ! -x ./.venv/bin/python ]; then
  echo "Refusing to run: Python executable is missing or not executable: ./.venv/bin/python" >&2
  exit 2
fi

if [ ! -f scripts/verify_external_cuda_operator_packet.py ]; then
  echo "Refusing to run: operator packet verifier is missing: scripts/verify_external_cuda_operator_packet.py" >&2
  exit 2
fi

if [ ! -f artifacts/review/external_cuda_operator_packet.json ]; then
  echo "Refusing to run: operator packet JSON is missing: artifacts/review/external_cuda_operator_packet.json" >&2
  exit 2
fi

if [ ! -f artifacts/review/real_adapter_cuda_training_handoff.sh ]; then
  echo "Refusing to run: CUDA training handoff shell is missing: artifacts/review/real_adapter_cuda_training_handoff.sh" >&2
  exit 2
fi

printf '\n== verify_external_cuda_operator_packet ==\n'
./.venv/bin/python scripts/verify_external_cuda_operator_packet.py --packet-json artifacts/review/external_cuda_operator_packet.json --expected-decision GO --json-output artifacts/review/external_cuda_operator_packet_verification.json

printf '\n== run_real_adapter_cuda_training_handoff ==\n'
bash artifacts/review/real_adapter_cuda_training_handoff.sh
